import type { z } from "zod";
import type { AddQueueItemSchema } from "./broadcast.schemas.js";
declare const queueTable: import("drizzle-orm/pg-core").PgTableWithColumns<{
    name: "broadcast_queue";
    schema: undefined;
    columns: {
        id: import("drizzle-orm/pg-core").PgColumn<{
            name: "id";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: true;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        videoId: import("drizzle-orm/pg-core").PgColumn<{
            name: "video_id";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        youtubeId: import("drizzle-orm/pg-core").PgColumn<{
            name: "youtube_id";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        title: import("drizzle-orm/pg-core").PgColumn<{
            name: "title";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        thumbnailUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "thumbnail_url";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        durationSecs: import("drizzle-orm/pg-core").PgColumn<{
            name: "duration_secs";
            tableName: "broadcast_queue";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        localVideoUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "local_video_url";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        hlsMasterUrl: import("drizzle-orm/pg-core").PgColumn<{
            name: "hls_master_url";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        videoSource: import("drizzle-orm/pg-core").PgColumn<{
            name: "video_source";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        isActive: import("drizzle-orm/pg-core").PgColumn<{
            name: "is_active";
            tableName: "broadcast_queue";
            dataType: "boolean";
            columnType: "PgBoolean";
            data: boolean;
            driverParam: boolean;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        sortOrder: import("drizzle-orm/pg-core").PgColumn<{
            name: "sort_order";
            tableName: "broadcast_queue";
            dataType: "number";
            columnType: "PgInteger";
            data: number;
            driverParam: string | number;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        addedAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "added_at";
            tableName: "broadcast_queue";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: true;
            hasDefault: true;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        scheduledAt: import("drizzle-orm/pg-core").PgColumn<{
            name: "scheduled_at";
            tableName: "broadcast_queue";
            dataType: "date";
            columnType: "PgTimestamp";
            data: Date;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: undefined;
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        scheduleLabel: import("drizzle-orm/pg-core").PgColumn<{
            name: "schedule_label";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
        validatorDeactivatedReason: import("drizzle-orm/pg-core").PgColumn<{
            name: "validator_deactivated_reason";
            tableName: "broadcast_queue";
            dataType: "string";
            columnType: "PgText";
            data: string;
            driverParam: string;
            notNull: false;
            hasDefault: false;
            isPrimaryKey: false;
            isAutoincrement: false;
            hasRuntimeDefault: false;
            enumValues: [string, ...string[]];
            baseColumn: never;
            identity: undefined;
            generated: undefined;
        }, {}, {}>;
    };
    dialect: "pg";
}>;
export declare const broadcastService: {
    snapshot(): import("./queue.engine.js").BroadcastSnapshot;
    listQueue(): Promise<(typeof queueTable.$inferSelect)[]>;
    addToQueue(item: z.infer<typeof AddQueueItemSchema>): Promise<{
        id: string;
        videoId: string | null;
        youtubeId: string;
        title: string;
        thumbnailUrl: string;
        durationSecs: number;
        localVideoUrl: string | null;
        hlsMasterUrl: string | null;
        videoSource: string;
        isActive: boolean;
        sortOrder: number;
        addedAt: Date;
        scheduledAt: Date | null;
        scheduleLabel: string | null;
        validatorDeactivatedReason: string | null;
    }>;
    removeFromQueue(id: string): Promise<{
        id: string;
        videoId: string | null;
        youtubeId: string;
        title: string;
        thumbnailUrl: string;
        durationSecs: number;
        localVideoUrl: string | null;
        hlsMasterUrl: string | null;
        videoSource: string;
        isActive: boolean;
        sortOrder: number;
        addedAt: Date;
        scheduledAt: Date | null;
        scheduleLabel: string | null;
        validatorDeactivatedReason: string | null;
    }>;
    reorder(itemIds: string[]): Promise<import("./queue.engine.js").BroadcastSnapshot>;
    toggleActive(id: string, isActive: boolean): Promise<{
        id: string;
        videoId: string | null;
        youtubeId: string;
        title: string;
        thumbnailUrl: string;
        durationSecs: number;
        localVideoUrl: string | null;
        hlsMasterUrl: string | null;
        videoSource: string;
        isActive: boolean;
        sortOrder: number;
        addedAt: Date;
        scheduledAt: Date | null;
        scheduleLabel: string | null;
        validatorDeactivatedReason: string | null;
    }>;
};
export {};
