import { z } from "zod";
export declare const ScheduleEntrySchema: z.ZodObject<{
    id: z.ZodString;
    title: z.ZodString;
    dayOfWeek: z.ZodNullable<z.ZodNumber>;
    startTime: z.ZodString;
    endTime: z.ZodNullable<z.ZodString>;
    contentType: z.ZodString;
    contentId: z.ZodNullable<z.ZodString>;
    isRecurring: z.ZodBoolean;
    isActive: z.ZodBoolean;
    createdAt: z.ZodString;
    scheduledDate: z.ZodNullable<z.ZodString>;
    priorityOverride: z.ZodBoolean;
}, "strip", z.ZodTypeAny, {
    id: string;
    title: string;
    isActive: boolean;
    createdAt: string;
    dayOfWeek: number | null;
    startTime: string;
    endTime: string | null;
    contentType: string;
    contentId: string | null;
    isRecurring: boolean;
    scheduledDate: string | null;
    priorityOverride: boolean;
}, {
    id: string;
    title: string;
    isActive: boolean;
    createdAt: string;
    dayOfWeek: number | null;
    startTime: string;
    endTime: string | null;
    contentType: string;
    contentId: string | null;
    isRecurring: boolean;
    scheduledDate: string | null;
    priorityOverride: boolean;
}>;
export declare const ListScheduleResponseSchema: z.ZodObject<{
    items: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        title: z.ZodString;
        dayOfWeek: z.ZodNullable<z.ZodNumber>;
        startTime: z.ZodString;
        endTime: z.ZodNullable<z.ZodString>;
        contentType: z.ZodString;
        contentId: z.ZodNullable<z.ZodString>;
        isRecurring: z.ZodBoolean;
        isActive: z.ZodBoolean;
        createdAt: z.ZodString;
        scheduledDate: z.ZodNullable<z.ZodString>;
        priorityOverride: z.ZodBoolean;
    }, "strip", z.ZodTypeAny, {
        id: string;
        title: string;
        isActive: boolean;
        createdAt: string;
        dayOfWeek: number | null;
        startTime: string;
        endTime: string | null;
        contentType: string;
        contentId: string | null;
        isRecurring: boolean;
        scheduledDate: string | null;
        priorityOverride: boolean;
    }, {
        id: string;
        title: string;
        isActive: boolean;
        createdAt: string;
        dayOfWeek: number | null;
        startTime: string;
        endTime: string | null;
        contentType: string;
        contentId: string | null;
        isRecurring: boolean;
        scheduledDate: string | null;
        priorityOverride: boolean;
    }>, "many">;
    total: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    total: number;
    items: {
        id: string;
        title: string;
        isActive: boolean;
        createdAt: string;
        dayOfWeek: number | null;
        startTime: string;
        endTime: string | null;
        contentType: string;
        contentId: string | null;
        isRecurring: boolean;
        scheduledDate: string | null;
        priorityOverride: boolean;
    }[];
}, {
    total: number;
    items: {
        id: string;
        title: string;
        isActive: boolean;
        createdAt: string;
        dayOfWeek: number | null;
        startTime: string;
        endTime: string | null;
        contentType: string;
        contentId: string | null;
        isRecurring: boolean;
        scheduledDate: string | null;
        priorityOverride: boolean;
    }[];
}>;
export declare const TIME_RE: RegExp;
export declare const CreateScheduleBodySchema: z.ZodEffects<z.ZodObject<{
    title: z.ZodString;
    dayOfWeek: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    startTime: z.ZodString;
    endTime: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contentType: z.ZodEnum<["live", "video", "playlist", "external"]>;
    contentId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isRecurring: z.ZodDefault<z.ZodBoolean>;
    isActive: z.ZodDefault<z.ZodBoolean>;
    scheduledDate: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    priorityOverride: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    title: string;
    isActive: boolean;
    startTime: string;
    contentType: "live" | "external" | "video" | "playlist";
    isRecurring: boolean;
    priorityOverride: boolean;
    dayOfWeek?: number | null | undefined;
    endTime?: string | null | undefined;
    contentId?: string | null | undefined;
    scheduledDate?: string | null | undefined;
}, {
    title: string;
    startTime: string;
    contentType: "live" | "external" | "video" | "playlist";
    isActive?: boolean | undefined;
    dayOfWeek?: number | null | undefined;
    endTime?: string | null | undefined;
    contentId?: string | null | undefined;
    isRecurring?: boolean | undefined;
    scheduledDate?: string | null | undefined;
    priorityOverride?: boolean | undefined;
}>, {
    title: string;
    isActive: boolean;
    startTime: string;
    contentType: "live" | "external" | "video" | "playlist";
    isRecurring: boolean;
    priorityOverride: boolean;
    dayOfWeek?: number | null | undefined;
    endTime?: string | null | undefined;
    contentId?: string | null | undefined;
    scheduledDate?: string | null | undefined;
}, {
    title: string;
    startTime: string;
    contentType: "live" | "external" | "video" | "playlist";
    isActive?: boolean | undefined;
    dayOfWeek?: number | null | undefined;
    endTime?: string | null | undefined;
    contentId?: string | null | undefined;
    isRecurring?: boolean | undefined;
    scheduledDate?: string | null | undefined;
    priorityOverride?: boolean | undefined;
}>;
export declare const UpdateScheduleBodySchema: z.ZodObject<{
    title: z.ZodOptional<z.ZodString>;
    dayOfWeek: z.ZodOptional<z.ZodNullable<z.ZodNumber>>;
    startTime: z.ZodOptional<z.ZodString>;
    endTime: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    contentType: z.ZodOptional<z.ZodEnum<["live", "video", "playlist", "external"]>>;
    contentId: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    isRecurring: z.ZodOptional<z.ZodBoolean>;
    isActive: z.ZodOptional<z.ZodBoolean>;
    scheduledDate: z.ZodOptional<z.ZodNullable<z.ZodString>>;
    priorityOverride: z.ZodOptional<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    title?: string | undefined;
    isActive?: boolean | undefined;
    dayOfWeek?: number | null | undefined;
    startTime?: string | undefined;
    endTime?: string | null | undefined;
    contentType?: "live" | "external" | "video" | "playlist" | undefined;
    contentId?: string | null | undefined;
    isRecurring?: boolean | undefined;
    scheduledDate?: string | null | undefined;
    priorityOverride?: boolean | undefined;
}, {
    title?: string | undefined;
    isActive?: boolean | undefined;
    dayOfWeek?: number | null | undefined;
    startTime?: string | undefined;
    endTime?: string | null | undefined;
    contentType?: "live" | "external" | "video" | "playlist" | undefined;
    contentId?: string | null | undefined;
    isRecurring?: boolean | undefined;
    scheduledDate?: string | null | undefined;
    priorityOverride?: boolean | undefined;
}>;
