/**
 * Viewer-side YouTube live embed failure telemetry.
 *
 * Why this exists: each TV / mobile device has its own per-device
 * `useLiveFailureFor` signal that drops it to the broadcast queue when its
 * iframe can't load. Individually those failures are silent to the admin —
 * they could be one viewer on a flaky connection OR a platform-wide YouTube
 * problem (geo-block flipped, video pulled, embed disabled mid-stream). This
 * module aggregates anonymous viewer failure pings so the admin Live Control
 * page can surface "47 devices reported the live stream failed in the last
 * 5 minutes" — letting them swap streams or stop the override before the
 * complaints come in.
 *
 * Storage: in-process ring buffer. No DB. Reports are inherently transient
 * (5-minute aggregation window) and losing them on restart is fine — viewers
 * will re-report within seconds when their next reconnect attempt fails.
 *
 * Privacy: we store an opaque per-device ID (random UUID generated by the
 * client and persisted there) and the client IP for rate-limiting only. No
 * user identity is recorded; admin views see counts only.
 *
 * Anti-abuse: per-IP rate limit caps spam from a single host, and the global
 * ring is bounded so a flood cannot exhaust memory.
 */

import { broadcastLiveEvent } from "./liveEvents";

export type LiveFailureSurface =
  | "tv-hero"
  | "tv-player"
  | "mobile-hero"
  | "mobile-player"
  | "unknown";

interface FailureReport {
  videoId: string;
  deviceId: string;
  surface: LiveFailureSurface;
  ip: string;
  reportedAt: number;
}

export interface LiveFailureStatsSnapshot {
  /** Active live videoId the stats are for, or null if no current focus. */
  videoId: string | null;
  /** Distinct devices that reported failure in the window. */
  deviceCount: number;
  /** Total reports (a single device may report multiple times across surfaces). */
  totalReports: number;
  /** Per-surface breakdown so the admin can see whether the hero or player is the culprit. */
  surfaces: Record<LiveFailureSurface, number>;
  /** Distinct client IPs — useful for sanity-checking single-network outages. */
  ipCount: number;
  /** Most-recent report timestamp (ms). */
  mostRecentAt: number | null;
  /** Window the stats cover (ms). */
  windowMs: number;
}

// ── Configuration ───────────────────────────────────────────────────────────

/**
 * Aggregation window the admin UI sees. Wider than the per-device 60 s TTL
 * because the admin needs to see sustained problems, not transient blips.
 */
const STATS_WINDOW_MS = 5 * 60 * 1000;

/** Hard cap so the ring cannot grow unbounded under abuse. */
const MAX_RING_SIZE = 5_000;

/** Per-IP rate limit (reports per minute). Generous — a misconfigured client could legitimately retry. */
const PER_IP_RATE_LIMIT = 30;
const PER_IP_WINDOW_MS = 60_000;

/** Debounce SSE broadcasts so a flurry of reports doesn't spam the wire. */
const SSE_DEBOUNCE_MS = 1_000;

// ── State ──────────────────────────────────────────────────────────────────

const reports: FailureReport[] = [];
const perIpHits = new Map<string, number[]>(); // ip -> array of timestamps within window
let pendingSseTimer: NodeJS.Timeout | null = null;
let lastBroadcastVideoId: string | null = null;
let lastBroadcastDeviceCount = 0;

function pruneRing(now: number): void {
  // Drop reports older than the stats window. Reports older than that are
  // useless for any consumer and just waste memory.
  const cutoff = now - STATS_WINDOW_MS;
  while (reports.length > 0 && reports[0]!.reportedAt < cutoff) {
    reports.shift();
  }
  // Hard cap as a defence-in-depth measure on top of rate-limiting.
  while (reports.length > MAX_RING_SIZE) {
    reports.shift();
  }
}

function pruneIpHits(ip: string, now: number): number[] {
  const cutoff = now - PER_IP_WINDOW_MS;
  const arr = perIpHits.get(ip) ?? [];
  const filtered = arr.filter((t) => t >= cutoff);
  if (filtered.length === 0) {
    perIpHits.delete(ip);
  } else {
    perIpHits.set(ip, filtered);
  }
  return filtered;
}

function scheduleSseBroadcast(videoId: string | null): void {
  if (pendingSseTimer) return;
  pendingSseTimer = setTimeout(() => {
    pendingSseTimer = null;
    const snapshot = getFailureStats(videoId);
    // Only broadcast when the viewer-impact count changes meaningfully —
    // re-emitting identical snapshots wastes downstream re-renders.
    if (
      snapshot.videoId === lastBroadcastVideoId &&
      snapshot.deviceCount === lastBroadcastDeviceCount
    ) {
      return;
    }
    lastBroadcastVideoId = snapshot.videoId;
    lastBroadcastDeviceCount = snapshot.deviceCount;
    broadcastLiveEvent("live-failure-stats", snapshot);
  }, SSE_DEBOUNCE_MS);
}

// ── Public API ─────────────────────────────────────────────────────────────

export interface RecordFailureInput {
  videoId: string;
  deviceId: string;
  surface: LiveFailureSurface;
  ip: string;
}

export type RecordFailureResult =
  | { ok: true }
  | { ok: false; reason: "rate_limited"; retryAfterSecs: number };

export function recordFailureReport(input: RecordFailureInput): RecordFailureResult {
  const now = Date.now();

  // Per-IP rate limit. We count BEFORE inserting so a runaway client gets
  // pushed back rather than gradually pollute the ring.
  const recent = pruneIpHits(input.ip, now);
  if (recent.length >= PER_IP_RATE_LIMIT) {
    return { ok: false, reason: "rate_limited", retryAfterSecs: 60 };
  }
  recent.push(now);
  perIpHits.set(input.ip, recent);

  pruneRing(now);
  reports.push({
    videoId: input.videoId,
    deviceId: input.deviceId,
    surface: input.surface,
    ip: input.ip,
    reportedAt: now,
  });

  scheduleSseBroadcast(input.videoId);
  return { ok: true };
}

const EMPTY_SURFACES: Record<LiveFailureSurface, number> = {
  "tv-hero": 0,
  "tv-player": 0,
  "mobile-hero": 0,
  "mobile-player": 0,
  unknown: 0,
};

/**
 * Returns aggregated failure stats for `videoId` within the stats window.
 * If `videoId` is null/empty, returns an empty snapshot so callers don't
 * need to special-case the off-air state.
 */
export function getFailureStats(videoId: string | null | undefined): LiveFailureStatsSnapshot {
  const now = Date.now();
  pruneRing(now);
  if (!videoId) {
    return {
      videoId: null,
      deviceCount: 0,
      totalReports: 0,
      surfaces: { ...EMPTY_SURFACES },
      ipCount: 0,
      mostRecentAt: null,
      windowMs: STATS_WINDOW_MS,
    };
  }
  const cutoff = now - STATS_WINDOW_MS;
  const devices = new Set<string>();
  const ips = new Set<string>();
  const surfaces: Record<LiveFailureSurface, number> = { ...EMPTY_SURFACES };
  let total = 0;
  let mostRecent: number | null = null;
  for (const r of reports) {
    if (r.videoId !== videoId || r.reportedAt < cutoff) continue;
    devices.add(r.deviceId);
    ips.add(r.ip);
    surfaces[r.surface] = (surfaces[r.surface] ?? 0) + 1;
    total++;
    if (mostRecent === null || r.reportedAt > mostRecent) mostRecent = r.reportedAt;
  }
  return {
    videoId,
    deviceCount: devices.size,
    totalReports: total,
    surfaces,
    ipCount: ips.size,
    mostRecentAt: mostRecent,
    windowMs: STATS_WINDOW_MS,
  };
}

/**
 * Test/debug helper. Not exported beyond this module's tests; safe to call
 * from anywhere but generally not useful in production.
 */
export function _resetForTests(): void {
  reports.length = 0;
  perIpHits.clear();
  if (pendingSseTimer) {
    clearTimeout(pendingSseTimer);
    pendingSseTimer = null;
  }
  lastBroadcastVideoId = null;
  lastBroadcastDeviceCount = 0;
}
