import { z } from "zod";
/**
 * Strongly-typed, validated environment. All env access in the
 * application MUST flow through `env`. New variables go here.
 */
declare const Env: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    PORT: z.ZodDefault<z.ZodNumber>;
    LOG_LEVEL: z.ZodDefault<z.ZodEnum<["fatal", "error", "warn", "info", "debug", "trace", "silent"]>>;
    DATABASE_URL: z.ZodString;
    JWT_ACCESS_SECRET: z.ZodString;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_ACCESS_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    JWT_REFRESH_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    JWT_ALGORITHM: z.ZodDefault<z.ZodEnum<["HS256", "RS256"]>>;
    REFRESH_TOKEN_STRICT_IP_CHECK: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    ADMIN_API_TOKEN: z.ZodOptional<z.ZodString>;
    ADMIN_API_TOKEN_ROLE: z.ZodDefault<z.ZodEnum<["system", "admin", "editor", "moderator", "user"]>>;
    ADMIN_API_TOKEN_IP_ALLOWLIST: z.ZodOptional<z.ZodString>;
    CORS_ORIGINS: z.ZodDefault<z.ZodString>;
    CORS_ORIGINS_EXTRA: z.ZodOptional<z.ZodString>;
    REDIS_URL: z.ZodOptional<z.ZodString>;
    BROADCAST_PRELOAD_LEAD_MS: z.ZodDefault<z.ZodNumber>;
    BROADCAST_FAILOVER_HLS_URL: z.ZodOptional<z.ZodString>;
    RATE_LIMIT_DEFAULT_PER_MINUTE: z.ZodDefault<z.ZodNumber>;
    RATE_LIMIT_AUTH_PER_MINUTE: z.ZodDefault<z.ZodNumber>;
    MAX_SSE_PER_IP: z.ZodDefault<z.ZodNumber>;
    MAX_WS_PER_IP: z.ZodDefault<z.ZodNumber>;
    BCRYPT_ROUNDS: z.ZodDefault<z.ZodNumber>;
    MEMORY_WARN_RSS_MB: z.ZodDefault<z.ZodNumber>;
    DB_POOL_MAX: z.ZodDefault<z.ZodNumber>;
    SENTRY_DSN: z.ZodOptional<z.ZodString>;
    RUN_MODE: z.ZodDefault<z.ZodEnum<["api", "worker", "all"]>>;
    SCHEDULED_NOTIF_POLL_MS: z.ZodDefault<z.ZodNumber>;
    SCHEDULED_NOTIF_MAX_ATTEMPTS: z.ZodDefault<z.ZodNumber>;
    TRANSCODER_POLL_MS: z.ZodDefault<z.ZodNumber>;
    TRANSCODER_DISABLE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    TRANSCODER_SCRATCH_DIR: z.ZodOptional<z.ZodString>;
    TRANSCODER_JOB_TIMEOUT_MS: z.ZodDefault<z.ZodNumber>;
    SMTP_HOST: z.ZodOptional<z.ZodString>;
    SMTP_PORT: z.ZodDefault<z.ZodNumber>;
    SMTP_USER: z.ZodOptional<z.ZodString>;
    SMTP_PASS: z.ZodOptional<z.ZodString>;
    SMTP_FROM_NAME: z.ZodDefault<z.ZodString>;
    SMTP_SECURE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    APP_BASE_URL: z.ZodDefault<z.ZodString>;
    VAPID_PUBLIC_KEY: z.ZodOptional<z.ZodString>;
    VAPID_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    VAPID_MAILTO: z.ZodDefault<z.ZodString>;
    EXPO_ACCESS_TOKEN: z.ZodOptional<z.ZodString>;
    CDN_BASE_URL: z.ZodOptional<z.ZodString>;
    REQUIRE_HLS_TOKEN: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    HLS_TOKEN_SECRET: z.ZodOptional<z.ZodString>;
    HLS_TOKEN_TTL_SECONDS: z.ZodDefault<z.ZodNumber>;
    HLS_MAX_CONCURRENT: z.ZodDefault<z.ZodNumber>;
    SHUTDOWN_DRAIN_MS: z.ZodDefault<z.ZodNumber>;
    YOUTUBE_API_KEY: z.ZodOptional<z.ZodString>;
    YOUTUBE_SYNC_INTERVAL_MINS: z.ZodDefault<z.ZodNumber>;
    YOUTUBE_SYNC_DISABLE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    PROD_SYNC_API_URL: z.ZodOptional<z.ZodString>;
    API_ORIGIN: z.ZodOptional<z.ZodString>;
    PROD_SYNC_INTERVAL_MS: z.ZodDefault<z.ZodNumber>;
    PROD_SYNC_DISABLE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    CLEANUP_RETENTION_HOURS: z.ZodDefault<z.ZodNumber>;
    CLEANUP_SWEEP_MS: z.ZodDefault<z.ZodNumber>;
    CLEANUP_DISABLE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
    CLEANUP_MAX_PER_SWEEP: z.ZodDefault<z.ZodNumber>;
    SEED_ADMIN_EMAIL: z.ZodOptional<z.ZodString>;
    SEED_ADMIN_PASSWORD: z.ZodOptional<z.ZodString>;
    SEED_ADMIN_FORCE: z.ZodDefault<z.ZodEffects<z.ZodUnion<[z.ZodBoolean, z.ZodString]>, boolean, string | boolean>>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    PORT: number;
    LOG_LEVEL: "fatal" | "error" | "warn" | "info" | "debug" | "trace" | "silent";
    DATABASE_URL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    JWT_ACCESS_TTL_SECONDS: number;
    JWT_REFRESH_TTL_SECONDS: number;
    JWT_ALGORITHM: "HS256" | "RS256";
    REFRESH_TOKEN_STRICT_IP_CHECK: boolean;
    ADMIN_API_TOKEN_ROLE: "system" | "admin" | "editor" | "moderator" | "user";
    CORS_ORIGINS: string;
    BROADCAST_PRELOAD_LEAD_MS: number;
    RATE_LIMIT_DEFAULT_PER_MINUTE: number;
    RATE_LIMIT_AUTH_PER_MINUTE: number;
    MAX_SSE_PER_IP: number;
    MAX_WS_PER_IP: number;
    BCRYPT_ROUNDS: number;
    MEMORY_WARN_RSS_MB: number;
    DB_POOL_MAX: number;
    RUN_MODE: "api" | "worker" | "all";
    SCHEDULED_NOTIF_POLL_MS: number;
    SCHEDULED_NOTIF_MAX_ATTEMPTS: number;
    TRANSCODER_POLL_MS: number;
    TRANSCODER_DISABLE: boolean;
    TRANSCODER_JOB_TIMEOUT_MS: number;
    SMTP_PORT: number;
    SMTP_FROM_NAME: string;
    SMTP_SECURE: boolean;
    APP_BASE_URL: string;
    VAPID_MAILTO: string;
    REQUIRE_HLS_TOKEN: boolean;
    HLS_TOKEN_TTL_SECONDS: number;
    HLS_MAX_CONCURRENT: number;
    SHUTDOWN_DRAIN_MS: number;
    YOUTUBE_SYNC_INTERVAL_MINS: number;
    YOUTUBE_SYNC_DISABLE: boolean;
    PROD_SYNC_INTERVAL_MS: number;
    PROD_SYNC_DISABLE: boolean;
    CLEANUP_RETENTION_HOURS: number;
    CLEANUP_SWEEP_MS: number;
    CLEANUP_DISABLE: boolean;
    CLEANUP_MAX_PER_SWEEP: number;
    SEED_ADMIN_FORCE: boolean;
    ADMIN_API_TOKEN?: string | undefined;
    ADMIN_API_TOKEN_IP_ALLOWLIST?: string | undefined;
    CORS_ORIGINS_EXTRA?: string | undefined;
    REDIS_URL?: string | undefined;
    BROADCAST_FAILOVER_HLS_URL?: string | undefined;
    SENTRY_DSN?: string | undefined;
    TRANSCODER_SCRATCH_DIR?: string | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASS?: string | undefined;
    VAPID_PUBLIC_KEY?: string | undefined;
    VAPID_PRIVATE_KEY?: string | undefined;
    EXPO_ACCESS_TOKEN?: string | undefined;
    CDN_BASE_URL?: string | undefined;
    HLS_TOKEN_SECRET?: string | undefined;
    YOUTUBE_API_KEY?: string | undefined;
    PROD_SYNC_API_URL?: string | undefined;
    API_ORIGIN?: string | undefined;
    SEED_ADMIN_EMAIL?: string | undefined;
    SEED_ADMIN_PASSWORD?: string | undefined;
}, {
    DATABASE_URL: string;
    JWT_ACCESS_SECRET: string;
    JWT_REFRESH_SECRET: string;
    NODE_ENV?: "development" | "test" | "production" | undefined;
    PORT?: number | undefined;
    LOG_LEVEL?: "fatal" | "error" | "warn" | "info" | "debug" | "trace" | "silent" | undefined;
    JWT_ACCESS_TTL_SECONDS?: number | undefined;
    JWT_REFRESH_TTL_SECONDS?: number | undefined;
    JWT_ALGORITHM?: "HS256" | "RS256" | undefined;
    REFRESH_TOKEN_STRICT_IP_CHECK?: string | boolean | undefined;
    ADMIN_API_TOKEN?: string | undefined;
    ADMIN_API_TOKEN_ROLE?: "system" | "admin" | "editor" | "moderator" | "user" | undefined;
    ADMIN_API_TOKEN_IP_ALLOWLIST?: string | undefined;
    CORS_ORIGINS?: string | undefined;
    CORS_ORIGINS_EXTRA?: string | undefined;
    REDIS_URL?: string | undefined;
    BROADCAST_PRELOAD_LEAD_MS?: number | undefined;
    BROADCAST_FAILOVER_HLS_URL?: string | undefined;
    RATE_LIMIT_DEFAULT_PER_MINUTE?: number | undefined;
    RATE_LIMIT_AUTH_PER_MINUTE?: number | undefined;
    MAX_SSE_PER_IP?: number | undefined;
    MAX_WS_PER_IP?: number | undefined;
    BCRYPT_ROUNDS?: number | undefined;
    MEMORY_WARN_RSS_MB?: number | undefined;
    DB_POOL_MAX?: number | undefined;
    SENTRY_DSN?: string | undefined;
    RUN_MODE?: "api" | "worker" | "all" | undefined;
    SCHEDULED_NOTIF_POLL_MS?: number | undefined;
    SCHEDULED_NOTIF_MAX_ATTEMPTS?: number | undefined;
    TRANSCODER_POLL_MS?: number | undefined;
    TRANSCODER_DISABLE?: string | boolean | undefined;
    TRANSCODER_SCRATCH_DIR?: string | undefined;
    TRANSCODER_JOB_TIMEOUT_MS?: number | undefined;
    SMTP_HOST?: string | undefined;
    SMTP_PORT?: number | undefined;
    SMTP_USER?: string | undefined;
    SMTP_PASS?: string | undefined;
    SMTP_FROM_NAME?: string | undefined;
    SMTP_SECURE?: string | boolean | undefined;
    APP_BASE_URL?: string | undefined;
    VAPID_PUBLIC_KEY?: string | undefined;
    VAPID_PRIVATE_KEY?: string | undefined;
    VAPID_MAILTO?: string | undefined;
    EXPO_ACCESS_TOKEN?: string | undefined;
    CDN_BASE_URL?: string | undefined;
    REQUIRE_HLS_TOKEN?: string | boolean | undefined;
    HLS_TOKEN_SECRET?: string | undefined;
    HLS_TOKEN_TTL_SECONDS?: number | undefined;
    HLS_MAX_CONCURRENT?: number | undefined;
    SHUTDOWN_DRAIN_MS?: number | undefined;
    YOUTUBE_API_KEY?: string | undefined;
    YOUTUBE_SYNC_INTERVAL_MINS?: number | undefined;
    YOUTUBE_SYNC_DISABLE?: string | boolean | undefined;
    PROD_SYNC_API_URL?: string | undefined;
    API_ORIGIN?: string | undefined;
    PROD_SYNC_INTERVAL_MS?: number | undefined;
    PROD_SYNC_DISABLE?: string | boolean | undefined;
    CLEANUP_RETENTION_HOURS?: number | undefined;
    CLEANUP_SWEEP_MS?: number | undefined;
    CLEANUP_DISABLE?: string | boolean | undefined;
    CLEANUP_MAX_PER_SWEEP?: number | undefined;
    SEED_ADMIN_EMAIL?: string | undefined;
    SEED_ADMIN_PASSWORD?: string | undefined;
    SEED_ADMIN_FORCE?: string | boolean | undefined;
}>;
export type AppEnv = z.infer<typeof Env>;
export declare const env: AppEnv;
export declare function isProd(): boolean;
export {};
