#!/usr/bin/env bash
# Temple TV JCTM — Android local.properties Generator
# Run this from the artifacts/mobile directory before opening the project in Android Studio.
# It detects your Android SDK path and writes android/local.properties automatically.

set -e

DEST="android/local.properties"

echo ""
echo "=== Temple TV Android SDK Setup ==="
echo ""

# ── 0. Generate android/ folder if missing (fresh clone) ──────────────────────
# Expo projects don't commit the native android/ folder — it's regenerated from
# app.json + plugins via `expo prebuild`. On a fresh clone we run prebuild here
# so the rest of the script (and Android Studio) has something to work with.
if [ ! -d "android" ]; then
  echo "No android/ folder found — running Expo prebuild to generate it."
  echo "(This reads app.json + plugins/ and creates a clean native project.)"
  echo ""

  if command -v pnpm >/dev/null 2>&1; then
    PREBUILD_CMD=(pnpm expo prebuild --platform android --no-install)
  elif command -v npx >/dev/null 2>&1; then
    PREBUILD_CMD=(npx expo prebuild --platform android --no-install)
  else
    echo "ERROR: Neither 'pnpm' nor 'npx' found on PATH."
    echo "       Install Node.js 20+ first, then re-run this script."
    exit 1
  fi

  echo "Running: ${PREBUILD_CMD[*]}"
  echo ""
  if ! "${PREBUILD_CMD[@]}"; then
    echo ""
    echo "ERROR: Expo prebuild failed. Fix the error above, then re-run this script."
    exit 1
  fi

  echo ""
  echo "android/ folder generated successfully."
  echo ""
else
  echo "Found existing android/ folder — skipping prebuild."
  echo "(Re-run 'pnpm expo prebuild --platform android --no-install' manually if you bumped versionCode.)"
  echo ""
fi

# ── 1. Already set via environment variables ──────────────────────────────────
if [ -n "$ANDROID_HOME" ] && [ -d "$ANDROID_HOME" ]; then
  SDK_PATH="$ANDROID_HOME"
  echo "Found SDK via \$ANDROID_HOME: $SDK_PATH"
elif [ -n "$ANDROID_SDK_ROOT" ] && [ -d "$ANDROID_SDK_ROOT" ]; then
  SDK_PATH="$ANDROID_SDK_ROOT"
  echo "Found SDK via \$ANDROID_SDK_ROOT: $SDK_PATH"
else
  # ── 2. Check common install locations ──────────────────────────────────────
  CANDIDATES=(
    "$HOME/Android/Sdk"          # Android Studio on Linux (default)
    "$HOME/android-sdk"
    "/opt/android-sdk"
    "/usr/lib/android-sdk"
    "$HOME/Library/Android/sdk"  # Android Studio on macOS
  )

  SDK_PATH=""
  for candidate in "${CANDIDATES[@]}"; do
    if [ -d "$candidate" ]; then
      SDK_PATH="$candidate"
      echo "Found SDK at: $SDK_PATH"
      break
    fi
  done
fi

# ── 3. Not found — ask the user ───────────────────────────────────────────────
if [ -z "$SDK_PATH" ]; then
  echo "Could not detect Android SDK automatically."
  echo ""
  echo "Hint: In Android Studio, go to File → Project Structure → SDK Location"
  echo "      to find your Android SDK path."
  echo ""
  read -rp "Enter your Android SDK path: " SDK_PATH

  if [ -z "$SDK_PATH" ] || [ ! -d "$SDK_PATH" ]; then
    echo ""
    echo "ERROR: Path '$SDK_PATH' does not exist."
    echo "       Install Android Studio first, then run this script again."
    exit 1
  fi
fi

# ── 4. Write local.properties ─────────────────────────────────────────────────
mkdir -p android

# Escape backslashes for Windows paths (keytool/Gradle on WSL)
ESCAPED_PATH="${SDK_PATH//\\/\\\\}"

cat > "$DEST" <<EOF
# Auto-generated by setup-local-properties.sh — do not commit this file.
sdk.dir=${ESCAPED_PATH}
EOF

echo ""
echo "Written: $DEST"
echo "  sdk.dir=${ESCAPED_PATH}"
echo ""

# ── 5. Configure Node.js path for Android Studio ──────────────────────────────
# Android Studio launched from a desktop icon does NOT inherit shell PATH,
# so Gradle often fails with: "command 'node' error=2 No such file or directory".
# Pin the absolute node path into android/gradle.properties to prevent this.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
NODE_HELPER="$SCRIPT_DIR/check-node-path.sh"

if [ -x "$NODE_HELPER" ]; then
  echo "── Configuring Node.js path for Android Studio ─────────────────────────────"
  echo ""
  bash "$NODE_HELPER" || echo "(node path helper exited with a warning — continuing)"
else
  echo "Note: $NODE_HELPER not found or not executable — skipping node path setup."
  echo "      If Android Studio later fails with 'command \"node\" error=2',"
  echo "      see the Troubleshooting section in ANDROID_STUDIO_BUILD.md."
  echo ""
fi

echo "You can now open the android/ folder in Android Studio."
echo "Gradle will pick up the SDK path (and node path, if set) automatically."
echo ""
echo "Next: Build → Generate Signed Bundle / APK → Android App Bundle"
echo "      Use android/temple-tv-release.keystore when prompted."
echo ""
