#!/usr/bin/env bash
# Temple TV JCTM — Android local.properties Generator
# Run this from the artifacts/mobile directory before opening the project in Android Studio.
# It detects your Android SDK path and writes android/local.properties automatically.

set -e

DEST="android/local.properties"

echo ""
echo "=== Temple TV Android SDK Setup ==="
echo ""

# ── 1. Already set via environment variables ──────────────────────────────────
if [ -n "$ANDROID_HOME" ] && [ -d "$ANDROID_HOME" ]; then
  SDK_PATH="$ANDROID_HOME"
  echo "Found SDK via \$ANDROID_HOME: $SDK_PATH"
elif [ -n "$ANDROID_SDK_ROOT" ] && [ -d "$ANDROID_SDK_ROOT" ]; then
  SDK_PATH="$ANDROID_SDK_ROOT"
  echo "Found SDK via \$ANDROID_SDK_ROOT: $SDK_PATH"
else
  # ── 2. Check common install locations ──────────────────────────────────────
  CANDIDATES=(
    "$HOME/Android/Sdk"          # Android Studio on Linux (default)
    "$HOME/android-sdk"
    "/opt/android-sdk"
    "/usr/lib/android-sdk"
    "$HOME/Library/Android/sdk"  # Android Studio on macOS
  )

  SDK_PATH=""
  for candidate in "${CANDIDATES[@]}"; do
    if [ -d "$candidate" ]; then
      SDK_PATH="$candidate"
      echo "Found SDK at: $SDK_PATH"
      break
    fi
  done
fi

# ── 3. Not found — ask the user ───────────────────────────────────────────────
if [ -z "$SDK_PATH" ]; then
  echo "Could not detect Android SDK automatically."
  echo ""
  echo "Hint: In Android Studio, go to File → Project Structure → SDK Location"
  echo "      to find your Android SDK path."
  echo ""
  read -rp "Enter your Android SDK path: " SDK_PATH

  if [ -z "$SDK_PATH" ] || [ ! -d "$SDK_PATH" ]; then
    echo ""
    echo "ERROR: Path '$SDK_PATH' does not exist."
    echo "       Install Android Studio first, then run this script again."
    exit 1
  fi
fi

# ── 4. Write local.properties ─────────────────────────────────────────────────
mkdir -p android

# Escape backslashes for Windows paths (keytool/Gradle on WSL)
ESCAPED_PATH="${SDK_PATH//\\/\\\\}"

cat > "$DEST" <<EOF
# Auto-generated by setup-local-properties.sh — do not commit this file.
sdk.dir=${ESCAPED_PATH}
EOF

echo ""
echo "Written: $DEST"
echo "  sdk.dir=${ESCAPED_PATH}"
echo ""
echo "You can now open the android/ folder in Android Studio."
echo "Gradle will pick up the SDK path automatically."
echo ""
echo "Next: Build → Generate Signed Bundle / APK → Android App Bundle"
echo "      Use android/temple-tv-release.keystore when prompted."
echo ""
