import {
  boolean,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

/**
 * Per-device watch-history table — stores a log of every video watched
 * by a TV / web client identified by a stable device UUID (generated by
 * the TV app on first load and persisted in localStorage).
 *
 * This is intentionally separate from `user_watch_history` (which
 * requires an authenticated userId) so unauthenticated TV viewers get
 * cross-session history persistence without needing to sign in.
 *
 * Uniqueness is enforced at the (device_id, video_id) pair: re-watching
 * a video updates the existing row rather than creating a duplicate.
 */
export const deviceWatchHistoryTable = pgTable(
  "device_watch_history",
  {
    id: text("id").primaryKey(),
    deviceId: text("device_id").notNull(),
    videoId: text("video_id").notNull(),
    title: text("title").notNull().default(""),
    thumbnailUrl: text("thumbnail_url").notNull().default(""),
    hlsUrl: text("hls_url"),
    positionSecs: integer("position_secs").notNull().default(0),
    durationSecs: integer("duration_secs").notNull().default(0),
    completed: boolean("completed").notNull().default(false),
    watchedAt: timestamp("watched_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    deviceVideoIdx: uniqueIndex("device_watch_history_device_video_idx").on(
      t.deviceId,
      t.videoId,
    ),
    // Composite covering index for the primary query pattern:
    // WHERE device_id = ? ORDER BY watched_at DESC LIMIT 100
    // Avoids a separate sort step that the plain device_id index requires.
    deviceWatchedIdx: index("device_watch_history_device_watched_idx").on(
      t.deviceId,
      t.watchedAt,
    ),
  }),
);

export type DeviceWatchHistory = typeof deviceWatchHistoryTable.$inferSelect;
export type DeviceWatchHistoryInsert =
  typeof deviceWatchHistoryTable.$inferInsert;
